spring:
  webflux:
    base-path: "/api/v1"

app:
  jwt:
    secret: "supa-dupa-mega-hyper-awesome-unbelievably-strong-secret"
  player:
    registration:
      debit-cents: 100000
  game:
    range:
      left-inclusive: 1
      right-inclusive: 10
