spring:
  webflux:
    base-path: "/api/v1"

app:
  group-id: "${project.groupId}"
  artifact-id: "${project.artifactId}"
  version: "${project.version}"
  jwt:
    secret: "supa-dupa-mega-hyper-awesome-unbelievably-strong-secret"
  game:
    registration-credits: 1000
    range:
      left-inclusive: 1
      right-inclusive: 10
    offset-to-prize-fun:
      0: "*10"
      1: "*5"
      2: "/2"
